---
sudo: false
language: ruby
cache: bundler
env:
  - GOOGLE_CLIENT_ID=xyz GOOGLE_CLIENT_SECRET=zyx
rvm:
  - 2.6.1
services:
  - postgresql
before_script:
  - psql -c 'create database hanami_app_test;' -U postgres
  - bundle exec hanami db migrate
script:
  - bundle exec rspec spec
